# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

byRcpp <- function(nr, frommat, totmat, summat, minmat, maxmat) {
    .Call(`_gjam_byRcpp`, nr, frommat, totmat, summat, minmat, maxmat)
}

condMVNRcpp <- function(cdex, gdex, xx, mu, sigma) {
    .Call(`_gjam_condMVNRcpp`, cdex, gdex, xx, mu, sigma)
}

tnormRcpp <- function(lo, hi, mu, sig) {
    .Call(`_gjam_tnormRcpp`, lo, hi, mu, sig)
}

trMVNmatrixRcpp <- function(avec, muvec, smat, lo, hi, whichSample, idxALL) {
    .Call(`_gjam_trMVNmatrixRcpp`, avec, muvec, smat, lo, hi, whichSample, idxALL)
}

rmvnormRcpp <- function(n, mu, sigma) {
    .Call(`_gjam_rmvnormRcpp`, n, mu, sigma)
}

solveRcpp <- function(A) {
    .Call(`_gjam_solveRcpp`, A)
}

getPmatKRcpp <- function(pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk) {
    .Call(`_gjam_getPmatKRcpp`, pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk)
}

fnZRcpp <- function(kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz) {
    .Call(`_gjam_fnZRcpp`, kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz)
}

invWbyRcpp <- function(sigsq, A) {
    .Call(`_gjam_invWbyRcpp`, sigsq, A)
}

dmvnormRcpp <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_gjam_dmvnormRcpp`, x, mean, sigma, logd)
}

randEffRcpp <- function(v, ngvec, sinv, CImat) {
    .Call(`_gjam_randEffRcpp`, v, ngvec, sinv, CImat)
}

